model:
  name: "meta-llama/Llama-2-7b-hf"
  
training:
  learning_rate: 2e-4
  batch_size: 4
  num_epochs: 3
  max_length: 512
  gradient_accumulation_steps: 4

lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

dataset:
  name: "lamini/lamini_docs"
  train_split: "train"
  eval_split: "validation"  # optional 